### ISSUE TITLE
Sending compassion

### ISSUE THREAD

**Issue by yogat3ch** [cflagg/cflagg.github.io#1]
Hey @cflagg,
Contacting you here because I don't have any other avenues of doing so. 
We were given the painful news midday today, needless to say it was a complete surprise. Was it a surprise to you too?
Tears were shed, it was definitely jarring and felt like a heartbreak and I think folks are still processing. I noticed you were at Neon for 7 years prior to making the leap to Virga, I can only imagine it was pretty gut-wrenching to have this happen in such a short time. 
Thank you for all of your hard work on the Continuous Integration, the custom feature taxonomy, and on organizing the team in Monday. Our Slackmojis will forever be more awesome because of your pro tips. 
I'm going to miss hearing vegan food ideas from a fellow vegan team member. 
Sending you compassion, fortitude, and faith that whatever is next for you will be in perfect alignment 🙏

**Comment by cflagg** [comment]
Hey @yogat3ch,

Thanks for reaching out, it means a lot. I was working on things Tuesday morning and by 1pm I was given the news, so yes it was a huge surprise. I hadn't had any discussions about performance or behavior issues before, so this is definitely a punch to the gut. I feel like a bit of a fool for leaving a steady job even though I was ready to move on and attracted to another place with a strong mission. I'm still in a bit of a daze as my wife and I prepare for another life transition. 

I appreciate learning so many things from you and others in our short time together! I already convinced some old coworkers about how easy it is to packegize their Shiny apps with the right libraries and automatically test it for free with GitHub Actions (since their repos are public). 

May our paths cross again. My wife has gone through the Jukai ceremony for the White Plum Zen tradition with a Boulder group. Perhaps you two can sit together if we overlap once we have moved back to Denver and you visit your mother.

Wishing the best for you all. I truly enjoyed connecting with everyone and was looking forward to the in-person retreat! I felt I had found a new tribe. 

I sent an invite on LinkedIn if you want to keep in touch that way. 

Thank you.  :pray:

**Comment by yogat3ch** [comment]
Hey @cflagg, 
I had a feeling it blindsided you - similarly to the way it did us -  as I noticed your last comments on the tech specs were just 2 hours before we met and were given the news. Sorry to hear that :(
Yeah, there hasn't been any feedback for anyone afaik. I think Jan-Mar was a 90-day "in the wild" observation period to see how the team performed. I feel like the "fire drill" the previous week might have been a test to see how quickly and efficiently we could respond to pressing demands, but that's purely speculation. I have no idea as to the reasons for the decision. 

Has your previous position been filled? Any chances on getting it back? Or do you want to pursue other work at this point? The good news is that the job market is very much favoring talented workers right now. Ya'll are moving very soon, I guess it will be easier to do everything necessary related to that without full time job demands though? Are you filing for unemployment?

That's awesome to hear you've shared some of the Shiny strategy! `golem` is a great framework for large apps! 

Interesting! We had a Rinzai Zen Roshi come speak to us at Sit-Heads (an online meditation group I'm a part of) last night. Your wife must be open-minded to also be involved with the Zen tradition. Does she have diverse spiritual interests?

I'll check LinkedIn for that request soon. I can reach out over their messaging platfor to let you know when I'll be in Denver. 

:-( Yeah, it's definitely saddening - sorry that this happened. I hope you find yourself among supportive friends and family as you and your wife make the transition.

Safe Journeys
